apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: godevsetup
  name: godevsetup
spec:
  replicas: 3
  selector:
    matchLabels:
      app: godevsetup
  template:
    metadata:
      labels:
        app: godevsetup
    spec:
      containers:
        - image: godevsetup
          name: godevsetup
          imagePullPolicy: IfNotPresent
---
kind: Service
apiVersion: v1
metadata:
  name: godevsetup-nodeport
spec:
  selector:
    app: godevsetup
  type: NodePort
  ports:
    - port: 9090
      targetPort: 8080
      nodePort: 30123
