---
kind: Service
apiVersion: v1
metadata:
  name: godevsetup-ext-loadbal
spec:
  selector:
    app: godevsetup
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30123
