apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: godevsetup
  name: godevsetup
spec:
  replicas: 3
  selector:
    matchLabels:
      app: godevsetup
  template:
    metadata:
      labels:
        app: godevsetup
    spec:
      containers:
      - image: localhost:5000/godevsetup:latest
        name: godevsetup
---
kind: Service
apiVersion: v1
metadata:
  name: godevsetup
spec:
  selector:
    app: godevsetup
  ports:
  - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: godevsetup-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: godevsetup
            port:
              number: 8080
---

